name: Build EXE inside Cloud
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Project Deps
        run: npm install

      - name: Install Build Tools
        run: npm install electron electron-builder --save-dev

      - name: Compile Vite Production Code
        run: npm run build

      - name: Packaging into Windows EXE
        run: npx electron-builder --config.win.target=portable --config.directories.output=dist_exe --config.files="['dist/**/*', 'main.js']"

      - name: Upload Finished EXE
        uses: actions/upload-artifact@v4
        with:
          name: CryptoClicker-Windows-EXE
          path: dist_exe/*.exe
